### ISSUE TITLE
Workflows - Test small data sets for workflows (ReadQC)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/ReadsQC#3]
create a small test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Chien-chi, please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. Thank you.

**Comment by chienchi** [comment]
commit 21ad21cb7ce97683885ab992cd00af0508324436

**Comment by Michal-Babins** [comment]
Here is an issue resulting from running ReadsQC base command with cromwell configuration on a virtual machine:

**Base Command**: `java -Dconfig.file=/opt/cromwell/config/cromwell.conf -jar /opt/cromwell/jar/cromwell.jar run -m metadata_out.json -i input.json rqcfilter.wdl`

**Resulting Failure**:
```
Exception in thread "main" java.lang.RuntimeException: java.io.InvalidClassException: tax.TaxTree; local class incompatible: stream classdesc serialVersionUID = -8478466459993996423, local class serialVersionUID = 5894416521711540017
        at fileIO.ReadWrite.readObject(ReadWrite.java:823)
        at fileIO.ReadWrite.read(ReadWrite.java:1282)
        at tax.TaxTree.sharedTree(TaxTree.java:2254)
        at tax.TaxTree.loadTaxTree(TaxTree.java:263)
        at tax.TaxTree.loadTaxTree(TaxTree.java:246)
        at jgi.RQCFilter2.printFileTaxonomy(RQCFilter2.java:2640)
        at jgi.RQCFilter2.taxFilter(RQCFilter2.java:2661)
        at jgi.RQCFilter2.process(RQCFilter2.java:1182)
        at jgi.RQCFilter2.main(RQCFilter2.java:73)
Caused by: java.io.InvalidClassException: tax.TaxTree; local class incompatible: stream classdesc serialVersionUID = -8478466459993996423, local class serialVersionUID = 5894416521711540017
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
        at fileIO.ReadWrite.readObject(ReadWrite.java:819)
```

**Java Version**:
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

**Explanation**:
Running the base command for ReadsQC appears to be running successfully up until the rqcfilter where there appears to be a failure to sync java versions between the machines as shown by different serialVersionUID's. The job hangs and does not finish.

**Comment by chienchi** [comment]
Michal add the rqc_test.wdl. pull request #5  merged.
